# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c729800771c321f490fda6509bdc5cc23e5c468c814888fe3213bf7768eee1cb4eb232ddd7717d85a590e9dcae231c2625cc048a1b88eae73aee33bfe6b2df0e

test:
  secret_key_base: 2584cbff78a87cfe73837d66c7cc7f1b744fa19a7b1bdf04e4d975f32e485545b6a33671fdb80ddd484b2376b51aa92e1be65416d6d6356d6c2984ab69b51d90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
